"""The README as a test: every path it walks still runs, and its figures exist.

The README is one long worked example, and the way it rots is silent — a keyword
renamed, a slot moved, a figure deleted, and the document still reads fine while
nothing in it runs. What is checked here is the calling contract rather than the
numbers: that the arguments the README passes are still accepted, that the slots
it reads are still there, and that the columns it prints are still named what it
says. The numbers themselves are regenerated by ``tools/make_readme_figures.py``
and graded against R by the rest of this suite.

Sizes are cut down from the README's, since none of these assertions is about
how many features there were. ``seed=SEED`` is kept because a smoke test that
fails one run in ten is worse than none.
"""

from __future__ import annotations

import re
from pathlib import Path

import matplotlib
import pandas as pd
import pytest

matplotlib.use("Agg")

import statassist as sa  # noqa: E402

#: The README's seed, so a failure here can be reproduced by running the README.
SEED = 2026
# Matches tools/make_readme_figures.py, which is what the README's numbers came from.
NOISE_SD = 2

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
FIG_DIR = REPO_ROOT / "docs" / "figures"

#: Images have to resolve for a reader who is on neither GitHub nor a checkout,
#: which is what PyPI is, and PyPI does not resolve a relative path.
RAW_URL_PREFIX = "https://raw.githubusercontent.com/hiows/STATassist-py/master/docs/figures/"

_MARKDOWN_IMAGE = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")


@pytest.fixture(autouse=True)
def _clean_figure():
    import matplotlib.pyplot as plt

    plt.close("all")
    yield
    plt.close("all")


class TestFigures:
    """The images the README points at, against the ones on disk."""

    def test_every_image_is_an_absolute_raw_url_so_pypi_can_render_it(self):
        referenced = _MARKDOWN_IMAGE.findall(README.read_text(encoding="utf-8"))
        assert referenced, "the README stopped showing any figure at all"
        for url in referenced:
            assert url.startswith(RAW_URL_PREFIX), url

    def test_every_referenced_figure_is_committed(self):
        referenced = _MARKDOWN_IMAGE.findall(README.read_text(encoding="utf-8"))
        for url in referenced:
            assert (FIG_DIR / url.removeprefix(RAW_URL_PREFIX)).is_file(), url

    def test_no_figure_is_carried_without_being_shown(self):
        """A figure nobody references is one the generator no longer produces."""
        text = README.read_text(encoding="utf-8")
        for path in FIG_DIR.glob("*.png"):
            assert path.name in text, path.name


@pytest.fixture(scope="module")
def two_group():
    sim = sa.simulate_two_groups(n_feats=8, n_up=2, n_down=2, seed=SEED)
    return sim, sa.compare_two_groups(**sim.args)


class TestPartOne:
    """Sections 1-9 and 14."""

    def test_the_simulator_arguments_go_straight_into_the_comparison(self, two_group):
        sim, comp_res = two_group
        assert set(sim.args) >= {"data", "feats", "group", "group_lv", "input_scale"}
        assert list(comp_res.effect.columns) == [
            "features",
            "x_center",
            "y_center",
            "fold_change",
            "log2fc",
        ]
        assert {"t_test", "wilcox_test", "robust_test"} <= set(comp_res.tests)

    def test_a_slot_is_reachable_as_an_attribute_and_as_a_key(self, two_group):
        _, comp_res = two_group
        assert comp_res.effect is comp_res["effect"]

    def test_the_verdict_can_be_scored_against_the_planted_answer(self, two_group):
        sim, comp_res = two_group
        sig = sa.estimate_significance(
            comp_res, test="t_test", log2fc_cutoff=1, pval_cutoff=0.05, adj_type="BH"
        )
        verdict = sig.significance
        assert list(verdict.columns) == [
            "features",
            "log2fc",
            "pvalue",
            "adj_pvalue",
            "is_signif",
        ]
        # Section 3 lines the two up by position, so they have to stay aligned.
        assert list(verdict["features"]) == list(sim.truth["features"])

    def test_the_plots_that_read_a_result_and_the_ones_that_read_the_data(self, two_group):
        sim, comp_res = two_group
        sig = sa.estimate_significance(comp_res, test="t_test")
        feats = list(sim.args["feats"])

        sa.draw_volcano_plot(sig)
        sa.draw_forest_plot(comp_res, test="t_test", type="estimate", feats=feats)
        sa.draw_forest_plot(comp_res, test="t_test", type="pvalue", feats=feats)
        sa.draw_grouped_boxplot(
            data=sim.args["data"],
            feats=feats,
            group=sim.args["group"],
            group_lv=sim.args["group_lv"],
        )
        sa.draw_butterfly_hist(
            data=sim.args["data"],
            feat=feats[0],
            group=sim.args["group"],
            group_lv=sim.args["group_lv"],
            type="both",
        )

    def test_the_heatmap_hands_back_the_clustering_the_readme_reads(self, two_group):
        sim, _ = two_group
        drawn = sa.draw_heatmap(
            data=sim.args["data"],
            group=sim.args["group"],
            group_lv=sim.args["group_lv"],
            scale="feature",
            hclust_method="ward.D2",
            show_sample_names=False,
        )
        assert {"matrix", "sample_order", "feat_order", "sample_hclust", "feat_hclust"} <= set(
            drawn
        )
        assert len(drawn["sample_order"]) == len(sim.args["group"])

    def test_the_omnibus_test_carries_a_post_hoc_stage_and_pairwise_tables(self):
        # The effect is planted wide of the default range so that a post-hoc
        # stage certainly runs: it only runs for features whose omnibus test
        # qualified, and there is nothing to draw when none of them did.
        sim = sa.simulate_multiple_groups(
            n_feats=4,
            n_control=20,
            n_treat=(20, 20),
            n_up=1,
            n_down=1,
            deg_log2fc=(5, 10),
            seed=SEED,
        )
        multi = sa.compare_multiple_groups(**sim.args)
        assert "posthoc" in multi and "pairwise" in multi
        assert set(multi.posthoc) == set(multi.tests)

        lead = multi.tests["anova_test"].sort_values("pval_adj")["features"].iloc[0]
        sa.draw_forest_plot(multi, test="anova_test", type="posthoc", feats=lead)
        sa.draw_volcano_plot(sa.estimate_significance(multi, test="anova_test"))

    def test_a_crossed_design_answers_per_term_and_draws_an_interaction(self):
        sim = sa.simulate_factorial_groups(n_feats=6, seed=SEED)
        control_label = {name: list(lv)[0] for name, lv in sim.args["factor_lv"].items()}
        fact = sa.compare_factorial_groups(**sim.args, control_label=control_label)
        assert "terms" in fact and "cells" in fact

        sig_term = sa.estimate_significance(fact, by="term")
        assert isinstance(sig_term.significance, dict)
        sa.draw_volcano_plot(sig_term)
        sa.draw_interaction_plot(fact, feats=fact.features[0], errorbar="se")

    def test_a_contingency_table_refuses_the_wrong_significance_function(self):
        sim = sa.simulate_categorical_groups(seed=SEED)
        cat = sa.compare_categorical_groups(**sim.args)
        assert {"chisq_test", "fisher_test"} <= set(cat.tests)
        assert isinstance(cat.as_table(), pd.DataFrame)

        with pytest.raises(Exception, match="must be a comparison result"):
            sa.estimate_significance(cat)

        by_cell = sa.estimate_categorical_significance(cat, by="cell")
        assert {"row_level", "col_level", "lift", "is_signif"} <= set(by_cell.significance.columns)
        sa.estimate_categorical_significance(cat, by="table", test="chisq_test")
        sa.draw_mosaic_plot(cat)

    def test_association_returns_one_square_matrix_set_per_method(self):
        cor_mat = sa.make_block_cor(
            n_features=6,
            blocks=[
                {"features": range(0, 3), "cor": 0.9},
                {"features": range(3, 5), "cor": 0.5, "against": range(5, 6)},
            ],
        )
        sim = sa.simulate_regression(n_pred=6, n_factor_pred=0, cor_mat=cor_mat, seed=SEED)
        feats = list(sim.args["predictors"])
        assoc = sa.summarize_association_stats(data=sim.args["data"], feats=feats)

        for method in assoc["design"]["methods"]:
            assert assoc[method]["corr"].shape == (len(feats), len(feats))
        sa.draw_corrplot(assoc["pearson"]["corr"])
        sa.draw_corrplot(assoc["pearson"]["corr"], pvalue=assoc["pearson"]["adj_pvalue"])


def _model_cor():
    """Blocks that straddle the planted predictors, as Part 2 of the README uses them."""
    return sa.make_block_cor(
        n_features=8,
        blocks=[
            {"features": range(1, 3), "cor": 0.8},
            {"features": range(4, 7), "cor": 0.5},
        ],
    )


@pytest.fixture(scope="module")
def regression():
    sim = sa.simulate_regression(cor_mat=_model_cor(), noise_sd=NOISE_SD, seed=SEED)
    data = sim.args["data"]
    split = sa.split_data(data=data, stratified=data["x_cat_1"], p_train=0.75, times=1, seed=SEED)
    only = split.datasets["Resample1"]
    return sim, split, only["train_data"], only["test_data"]


@pytest.fixture(scope="module")
def classification():
    sim = sa.simulate_classification(cor_mat=_model_cor(), seed=SEED)
    data = sim.args["data"]
    split = sa.split_data(
        data=data,
        stratified=data[sim.args["outcome"]],
        p_train=0.75,
        times=1,
        seed=SEED,
    )
    only = split.datasets["Resample1"]
    return sim, only["train_data"], only["test_data"]


class TestPartTwo:
    """Sections 15-25."""

    def test_the_split_reports_what_it_actually_reached(self, regression):
        _, split, train_data, test_data = regression
        assert len(train_data.index) + len(test_data.index) == len(split.full_data.index)
        assert "achieved_p" in split.parameters

    def test_the_truth_table_names_the_nulls_that_correlate_with_a_signal(self, regression):
        sim, *_ = regression
        truth = sim.truth
        assert {"role", "beta", "max_cor_signal"} <= set(truth.columns)
        # Section 15 turns on there being one, which the correlation blocks plant.
        pulled = truth[(truth["role"] == "null") & (truth["max_cor_signal"] > 0)]
        assert not pulled.empty

    def test_a_fitted_model_answers_coef_and_predict_whatever_engine_it_used(
        self, regression, classification
    ):
        sim_reg, _, train_data, test_data = regression
        outcome = sim_reg.args["outcome"]
        predictors = list(sim_reg.args["predictors"])

        lin = sa.fit_linear_regression(
            data=train_data, outcome=outcome, predictors=predictors, cv=False
        )
        assert {"terms", "estimate", "pval"} <= set(lin.coef().columns)
        assert len(lin.predict(newdata=test_data)) == len(test_data.index)
        # `fit` is a handle, not a slot: it must not travel in the JSON-able form.
        assert lin.fit is not None
        assert "fit" not in lin.to_dict()

        sim_cls, cls_train, cls_test = classification
        log_fit = sa.fit_logistic_regression(
            data=cls_train,
            outcome=sim_cls.args["outcome"],
            predictors=list(sim_cls.args["predictors"]),
            outcome_lv=sim_cls.args["outcome_lv"],
            cv=False,
        )
        assert {"odds_ratio", "or_lower_conf", "or_upper_conf"} <= set(log_fit.coef().columns)
        assert set(log_fit.predict(newdata=cls_test, type="prob").columns) == set(
            sim_cls.args["outcome_lv"]
        )
        assert len(log_fit.predict(newdata=cls_test, type="response")) == len(cls_test.index)
        assert set(log_fit.predict(newdata=cls_test, type="raw")) <= set(sim_cls.args["outcome_lv"])

    def test_a_penalized_fit_omits_the_inference_it_cannot_honestly_give(self, regression):
        _, _, train_data, _ = regression
        sim_reg, *_ = regression
        lasso = sa.fit_elastic_net(
            data=train_data,
            outcome=sim_reg.args["outcome"],
            predictors=list(sim_reg.args["predictors"]),
            penalty="lasso",
            lambda_=(0.01, 0.1, 0.5, 1.0, 2.0),
            cv=True,
            seed=SEED,
        )
        columns = set(lasso.coef().columns)
        assert "selected" in columns
        assert not columns & {"stderr", "pval", "lower_conf", "upper_conf"}

    def test_both_searches_return_the_same_contract_on_a_candidates_axis(self, classification):
        sim_cls, cls_train, _ = classification
        shared = {
            "data": cls_train,
            "outcome": sim_cls.args["outcome"],
            "predictors": list(sim_cls.args["predictors"]),
            "outcome_lv": sim_cls.args["outcome_lv"],
            "model": "logistic",
        }
        rfe = sa.perform_rfe(**shared, seed=SEED)
        step = sa.perform_stepwise(**shared, criterion="AIC")

        for search in (rfe, step):
            assert list(search.ranking["candidates"]) != []
            assert set(search.selected) <= set(search.candidates)
            assert "n_vars" in search.profile.columns
            assert bool(search.profile["chosen"].any())
        # Section 19 leans on this: nothing was held out, so nothing was resampled.
        assert step.resampling is None

    def test_models_are_scored_on_the_same_held_out_rows(self, regression, classification):
        sim_reg, _, train_data, test_data = regression
        outcome = sim_reg.args["outcome"]
        kept = list(
            sa.perform_rfe(
                data=train_data,
                outcome=outcome,
                predictors=list(sim_reg.args["predictors"]),
                seed=SEED,
            ).selected
        )

        eval_reg = sa.evaluate_regression_models(
            baseline_model=sa.fit_linear_regression(
                data=train_data, outcome=outcome, predictors=kept, cv=False
            ),
            new_models={
                "rf": sa.fit_rf(
                    data=train_data, outcome=outcome, predictors=kept, cv=False, seed=SEED
                )
            },
            newdata=test_data,
            answer=test_data[outcome],
            baseline_label="linear",
        )
        assert "curves" not in eval_reg
        assert {"model", "cor", "r_squared", "rmse", "calib_slope"} <= set(eval_reg.metrics.columns)
        assert set(eval_reg.metrics["n_used"]) == {len(test_data.index)}
        sa.draw_prediction_plot(eval_reg, type="overlay", anno_corr=True, anno_rsq=True)

        sim_cls, cls_train, cls_test = classification
        cls_outcome = sim_cls.args["outcome"]
        outcome_lv = sim_cls.args["outcome_lv"]
        cls_kept = list(sim_cls.truth.loc[sim_cls.truth["role"] != "null", "predictors"])
        shared = {
            "data": cls_train,
            "outcome": cls_outcome,
            "predictors": cls_kept,
            "outcome_lv": outcome_lv,
            "cv": False,
        }
        eval_cls = sa.evaluate_classification_models(
            baseline_model=sa.fit_logistic_regression(**shared),
            new_models={"rf": sa.fit_rf(**shared, seed=SEED)},
            newdata=cls_test,
            answer=cls_test[cls_outcome],
            outcome_lv=outcome_lv,
            baseline_label="logistic",
        )
        assert "curves" in eval_cls
        assert {"auc", "brier", "accuracy"} <= set(eval_cls.metrics.columns)
        assert {"delta_auc", "idi", "nri"} <= set(eval_cls.comparisons.columns)
        sa.draw_roc_curve(eval_cls, anno_auc=True)


@pytest.fixture(scope="module")
def reduction_data():
    cor_mat = sa.make_block_cor(
        n_features=8,
        blocks=[
            {"features": range(0, 2), "cor": 0.8},
            {"features": range(2, 5), "cor": 0.5},
            {"features": range(6, 8), "cor": 0.9},
        ],
    )
    sim = sa.simulate_classification(cor_mat=cor_mat, seed=SEED)
    feats = [c for c in sim.args["predictors"] if c in sim.args["data"].select_dtypes("number")]
    return sim.args["data"], feats


class TestPartThree:
    """Sections 26-27."""

    def test_a_rotation_carries_variance_and_an_embedding_does_not(self, reduction_data):
        data, feats = reduction_data
        pca = sa.perform_pca(
            data=data, feats=feats, embedding_scale="features", center=True, scale=True
        )
        assert "variance" in pca and "loadings" in pca
        assert list(pca.scores["points"]) == feats
        sa.draw_dim_reduction_plot(pca, anno_points=True)

        tsne = sa.perform_tsne(
            data=data,
            feats=feats,
            embedding_scale="features",
            center=True,
            scale=True,
            perplexity=(len(feats) - 1) / 3,
            seed=SEED,
        )
        assert "variance" not in tsne
        sa.draw_dim_reduction_plot(tsne, anno_points=True)

    def test_umap_answers_on_the_same_points_when_the_extra_is_installed(self, reduction_data):
        pytest.importorskip("umap", reason="`perform_umap()` needs the optional `umap` extra")
        data, feats = reduction_data
        umap_res = sa.perform_umap(
            data=data, feats=feats, embedding_scale="features", n_neighbors=3, seed=SEED
        )
        assert list(umap_res.scores["points"]) == feats
        sa.draw_dim_reduction_plot(umap_res, anno_points=True)

    def test_a_clustering_lands_on_the_same_points_the_embedding_did(self):
        sim = sa.simulate_two_groups(n_feats=20, n_up=5, n_down=5, deg_log2fc=(5, 10), seed=SEED)
        pca = sa.perform_pca(
            data=sim.args["data"], feats=sim.args["feats"], embedding_scale="samples"
        )
        clust = sa.cluster_kmeans(
            data=pca.scores,
            feats=["PC1", "PC2"],
            cluster_scale="samples",
            n_clust=len(sim.args["group_lv"]),
            seed=SEED,
        )
        assert {"points", "cluster", "silhouette"} <= set(clust.assignments.columns)
        assert list(clust.points) == list(pca.points)

        sa.draw_dim_reduction_plot(pca, group=sim.args["group"], group_lv=sim.args["group_lv"])
        sa.draw_dim_reduction_plot(pca, cluster_result=clust)
