"""Shared helper layer: validation, adjustment, result contracts, randomness.

Everything a public STATassist function is built on. Ported from the R package's
``utils_validate.R`` and ``result.R``, which between them are what twelve public
functions there have in common.
"""

from __future__ import annotations

from .contingency import (
    DISCORDANT_PAIR_MIN,
    EXPECTED_COUNT_FLOOR,
    EXPECTED_COUNT_MIN,
    EXPECTED_LT5_MAX_PROP,
    MAX_CATEGORY_LEVELS,
    REPEATED_CELL_MIN,
    CategoricalInput,
    categorical_cells,
    categorical_condition_counts,
    categorical_counts,
    categorical_shared_lv,
    check_level_count,
    diagnose_discordance,
    diagnose_expected,
    diagnose_repeated,
    expected_independence,
    expected_symmetry,
    finite_or_na,
    validate_categorical_input,
)
from .contracts import (
    association_columns,
    categorical_cell_columns,
    categorical_nulls,
    categorical_test_columns,
    cell_table_columns,
    pairwise_table_columns,
    posthoc_stat_columns,
    posthoc_table_columns,
    term_table_columns,
    test_table_columns,
)
from .errors import (
    SaError,
    SaInternalError,
    SaValueError,
    SaWarning,
)
from .factorial import (
    FACT_TOL,
    ContrastSkeleton,
    fact_cell_index,
    fact_cell_labels,
    fact_collapse,
    fact_component,
    fact_contrast_skeleton,
    fact_control_first,
    fact_grid,
    fact_subsets,
    fact_term_effect,
    fact_term_labels,
    fact_terms,
)
from .padjust import P_ADJUST_METHODS, p_adjust
from .random import SaRandom
from .result import (
    SaComparison,
    SaDiagnosis,
    SaResult,
    SaSimulation,
    SaSplit,
    metadata,
    new_comparison,
    pick_test,
)
from .rstats import MAD_CONSTANT, mad
from .tables import add_padj, feature_table, level_pairs, na_row, posthoc_table, stat_row
from .validate import (
    UNSET,
    Alignment,
    Pairing,
    RowVector,
    WideInput,
    align_by_subject,
    check_count,
    check_feat_names,
    check_flag,
    check_lim,
    check_margin,
    check_num_vector,
    check_p_adjust,
    check_pvalues,
    check_range,
    check_scalar_num,
    control_first,
    fmt_est,
    fmt_num,
    pair_by_id,
    pair_by_order,
    resolve_row_vector,
    validate_wide_input,
)

__all__ = [
    "DISCORDANT_PAIR_MIN",
    "EXPECTED_COUNT_FLOOR",
    "EXPECTED_COUNT_MIN",
    "EXPECTED_LT5_MAX_PROP",
    "FACT_TOL",
    "MAD_CONSTANT",
    "MAX_CATEGORY_LEVELS",
    "P_ADJUST_METHODS",
    "REPEATED_CELL_MIN",
    "UNSET",
    "Alignment",
    "CategoricalInput",
    "ContrastSkeleton",
    "Pairing",
    "RowVector",
    "SaComparison",
    "SaDiagnosis",
    "SaError",
    "SaInternalError",
    "SaRandom",
    "SaResult",
    "SaSimulation",
    "SaSplit",
    "SaValueError",
    "SaWarning",
    "WideInput",
    "add_padj",
    "align_by_subject",
    "association_columns",
    "categorical_cell_columns",
    "categorical_cells",
    "categorical_condition_counts",
    "categorical_counts",
    "categorical_nulls",
    "categorical_shared_lv",
    "categorical_test_columns",
    "cell_table_columns",
    "check_count",
    "check_feat_names",
    "check_flag",
    "check_level_count",
    "check_lim",
    "check_margin",
    "check_num_vector",
    "check_p_adjust",
    "check_pvalues",
    "check_range",
    "check_scalar_num",
    "control_first",
    "diagnose_discordance",
    "diagnose_expected",
    "diagnose_repeated",
    "expected_independence",
    "expected_symmetry",
    "fact_cell_index",
    "fact_cell_labels",
    "fact_collapse",
    "fact_component",
    "fact_contrast_skeleton",
    "fact_control_first",
    "fact_grid",
    "fact_subsets",
    "fact_term_effect",
    "fact_term_labels",
    "fact_terms",
    "feature_table",
    "finite_or_na",
    "fmt_est",
    "fmt_num",
    "level_pairs",
    "mad",
    "metadata",
    "na_row",
    "new_comparison",
    "p_adjust",
    "pair_by_id",
    "pair_by_order",
    "pairwise_table_columns",
    "pick_test",
    "posthoc_stat_columns",
    "posthoc_table",
    "posthoc_table_columns",
    "resolve_row_vector",
    "stat_row",
    "term_table_columns",
    "test_table_columns",
    "validate_categorical_input",
    "validate_wide_input",
]
