"""Regenerate every figure and printed output the top-level README shows.

The README is a workflow document: each section runs on data whose answer was
planted, so the verdict it reports can be scored rather than trusted. Nothing in
it may be transcribed from the R package or edited by hand, which is what this
script is for - it runs the README end to end, writes the figures next to it and
dumps every table and repr the prose quotes into one text file.

Run it from the repository root::

    python tools/make_readme_figures.py

``perform_umap()`` needs the ``umap`` extra. When it is not installed the UMAP
section is skipped and says so, the same way the docstring example does, so the
rest of the figures still regenerate on a plain install.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

import statassist as sa  # noqa: E402

# One seed for every simulation in the README, so a reader who copies a block
# gets the numbers the prose quotes.
SEED = 2026

# The figures are read on GitHub and on PyPI rather than zoomed into, so they are
# sized for a README column rather than for print.
DPI = 130

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FIG_DIR = REPO_ROOT / "docs" / "figures"
DEFAULT_TEXT_OUT = REPO_ROOT / "docs" / "readme_outputs.txt"

# The two-group example is the one the top of the README opens with: thirty
# features, sixteen of them moved, so the verdict has both kinds of mistake
# available to it.
N_FEATS_TWO = 30
N_MOVED_EACH_WAY = 8

# How many features the plots that draw one panel per feature are given.
N_SHOWN = 10

# The cutoffs the README thresholds on. They are the defaults of
# `estimate_significance()`, named here because the prose quotes them.
LOG2FC_CUTOFF = 1.0
PVAL_CUTOFF = 0.05

# The correlation planted between predictors, so a null predictor that
# correlates with a planted one can be pointed at by name later.
COR_STRONG = 0.8
COR_MODERATE = 0.5
COR_TIGHT = 0.9

# Below the simulator's own default of 3. Part 2 is read for what the tables and
# the prediction plot look like when a model has something to find, and at the
# default the residual swamps the planted coefficients on 200 rows.
NOISE_SD = 2

CV_ARGS: dict[str, Any] = {
    "cv": True,
    "cv_method": "repeated_kfold",
    "n_fold": 10,
    "n_repeat": 3,
    "seed": SEED,
}

# A penalty grid wide enough that the resampling has something to choose between.
# Left to itself the engine can settle on a lambda small enough that the fit is
# the unpenalized one, which says nothing about what a penalty does.
LAMBDA_GRID = (0.01, 0.1, 0.5, 1.0, 2.0)


class Notes:
    """Everything the README prose quotes, in the order the README quotes it."""

    def __init__(self) -> None:
        self._blocks: list[tuple[str, str]] = []

    def add(self, tag: str, value: Any) -> None:
        text = value if isinstance(value, str) else repr(value)
        self._blocks.append((tag, text.rstrip()))
        print(f"  recorded {tag}")

    def show(self, tag: str, value: Any) -> None:
        """Record the ``str()`` of a result, which is what a reader would see."""
        self.add(tag, str(value))

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        rule = "=" * 79
        parts = [
            "Generated by tools/make_readme_figures.py.",
            "Every block below is quoted verbatim by README.md - edit the script,",
            "rerun it and paste, rather than editing either file by hand.",
            "",
        ]
        for tag, text in self._blocks:
            parts.extend([rule, tag, rule, "", text, ""])
        path.write_text("\n".join(parts), encoding="utf-8")


def _shown(path: Path) -> str:
    """The path as the reader would type it, when it sits inside the repository."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def save(fig_dir: Path, name: str) -> None:
    """Write the current figure out under the README's naming convention."""
    fig_dir.mkdir(parents=True, exist_ok=True)
    path = fig_dir / f"README-{name}.png"
    plt.gcf().savefig(path, dpi=DPI, bbox_inches="tight")
    plt.close("all")
    print(f"  wrote {_shown(path)}")


def figure(width: float, height: float) -> None:
    plt.close("all")
    plt.figure(figsize=(width, height))


def two_groups(fig_dir: Path, notes: Notes) -> None:
    """Sections 1-6: the comparison, its verdict, and the plots that read them."""
    print("two-group comparison")
    sim = sa.simulate_two_groups(
        n_feats=N_FEATS_TWO,
        n_up=N_MOVED_EACH_WAY,
        n_down=N_MOVED_EACH_WAY,
        seed=SEED,
    )
    comp_res = sa.compare_two_groups(**sim.args)
    notes.show("s01 comp_res", comp_res)
    notes.add("s01 comp_res.effect.head(4)", comp_res.effect.head(4))

    sig = sa.estimate_significance(
        comp_res,
        test="t_test",
        log2fc_cutoff=LOG2FC_CUTOFF,
        pval_cutoff=PVAL_CUTOFF,
        adj_type="BH",
    )
    notes.show("s02 sig", sig)
    verdict = sig.significance

    figure(7.0, 6.0)
    sa.draw_volcano_plot(sig)
    save(fig_dir, "volcano")

    # Section 3 - score the verdict against the answer that was planted.
    planted = sim.truth["direction"].to_numpy() != "none"
    called = verdict["is_signif"].fillna(False).to_numpy()
    notes.add(
        "s03 planted vs called",
        pd.crosstab(
            pd.Series(planted, name="planted"),
            pd.Series(called, name="called"),
        ),
    )

    recall = {
        name: float(
            sa.estimate_significance(comp_res, test=name)
            .significance["is_signif"]
            .fillna(False)
            .to_numpy()[planted]
            .mean()
        )
        for name in comp_res.tests
    }
    notes.add("s03 recall by test family", recall)

    missed = planted & ~called
    notes.add("s03 sim.truth[missed]", sim.truth[missed])
    notes.add("s03 verdict[missed]", verdict[missed])

    # Section 4 - the plots that read the data rather than a result.
    shown = list(sim.args["feats"])[:N_SHOWN]
    figure(9.0, 5.5)
    sa.draw_grouped_boxplot(
        data=sim.args["data"],
        feats=shown,
        group=sim.args["group"],
        group_lv=sim.args["group_lv"],
    )
    save(fig_dir, "boxplot")

    # Section 13, drawn here because it reads the same ten features from the same
    # simulation: the spread each group has, and then the one number standing for
    # it, so the two pictures can be read against each other.
    figure(9.0, 5.5)
    sa.draw_grouped_barplot(
        data=sim.args["data"],
        feats=shown,
        group=sim.args["group"],
        group_lv=sim.args["group_lv"],
        errorbar="se",
    )
    save(fig_dir, "barplot")

    # The feature the verdict is most certain about, so the two groups visibly
    # separate rather than being picked by name.
    strongest = str(verdict.sort_values("adj_pvalue")["features"].iloc[0])
    notes.add("s04 strongest feature", strongest)
    figure(7.5, 5.5)
    sa.draw_butterfly_hist(
        data=sim.args["data"],
        feat=strongest,
        group=sim.args["group"],
        group_lv=sim.args["group_lv"],
        type="both",
    )
    save(fig_dir, "butterfly")

    # Section 5 - one function, two views of the same table.
    figure(7.5, 6.0)
    sa.draw_forest_plot(comp_res, test="t_test", type="estimate", feats=shown, sort_by="pvalue")
    save(fig_dir, "forest-estimate")

    figure(7.5, 6.0)
    sa.draw_forest_plot(comp_res, test="t_test", type="pvalue", feats=shown, sort_by="pvalue")
    save(fig_dir, "forest-pvalue")

    # Section 6 - the heatmap, and the clustering it hands back.
    figure(9.0, 7.0)
    drawn = sa.draw_heatmap(
        data=sim.args["data"],
        group=sim.args["group"],
        group_lv=sim.args["group_lv"],
        scale="feature",
        hclust_method="ward.D2",
        show_sample_names=False,
    )
    save(fig_dir, "heatmap")
    notes.add("s06 drawn.keys()", sorted(drawn))
    notes.add("s06 drawn['matrix'].index", list(drawn["matrix"].index[:5]))
    # The plot was never told where the groups are. Whether it put them together
    # anyway is answered by the longest unbroken run of each along the columns.
    ordered = pd.Series(pd.Series(sim.args["group"]).to_numpy()[drawn["sample_order"]])
    runs = ordered.groupby((ordered != ordered.shift()).cumsum())
    longest = (
        pd.DataFrame({"group": [g.iloc[0] for _, g in runs], "run": [len(g) for _, g in runs]})
        .groupby("group")["run"]
        .max()
    )
    notes.add("s06 longest run per group along sample_order", longest)


def multiple_groups(fig_dir: Path, notes: Notes) -> None:
    """Section 7: an omnibus test and the post-hoc stage that shares its assumptions."""
    print("multi-group comparison")
    sim = sa.simulate_multiple_groups(
        n_feats=N_SHOWN,
        n_control=50,
        n_treat=(50, 50, 50),
        n_up=3,
        n_down=3,
        seed=SEED,
    )
    multi = sa.compare_multiple_groups(**sim.args)
    notes.show("s07 multi", multi)

    anova = multi.tests["anova_test"]
    notes.add(
        "s07 multi.tests['anova_test']",
        anova[["features", "n_used", "f_stat", "eta_sq", "pval_adj"]],
    )

    # The feature the omnibus test is most certain about, so the contrasts below
    # have something to separate.
    lead = str(anova.sort_values("pval_adj")["features"].iloc[0])
    notes.add("s07 leading feature", lead)
    posthoc = multi.posthoc["anova_test"]
    notes.add(
        "s07 posthoc for the leading feature",
        posthoc.loc[posthoc["features"] == lead, ["contrast", "estimate", "pval_adj"]],
    )
    notes.add("s07 pairwise contrast labels", list(multi.pairwise["anova_test"]))

    figure(7.5, 4.5)
    sa.draw_forest_plot(multi, test="anova_test", type="posthoc", feats=lead, sort_by="pvalue")
    save(fig_dir, "multi-posthoc")

    sig_multi = sa.estimate_significance(
        multi, test="anova_test", pval_cutoff=PVAL_CUTOFF, adj_type="BH"
    )
    notes.show("s07 sig_multi", sig_multi)
    figure(7.0, 6.0)
    sa.draw_volcano_plot(sig_multi)
    save(fig_dir, "multi-volcano")


def factorial_groups(fig_dir: Path, notes: Notes) -> None:
    """Section 8: two crossed factors, with the answer planted per model term."""
    print("factorial comparison")
    sim = sa.simulate_factorial_groups(seed=SEED)
    # Naming a reference level per factor fixes what `$effect` is measured against.
    # The simulators list the reference first, so this states the default rather
    # than changing it.
    control_label = {name: list(levels)[0] for name, levels in sim.args["factor_lv"].items()}
    notes.add("s08 control_label", control_label)

    fact = sa.compare_factorial_groups(**sim.args, control_label=control_label)
    notes.show("s08 fact", fact)
    notes.add("s08 fact.effect.head(3)", fact.effect.head(3))

    # A crossover: both main effects flat, the interaction moved. It is the one
    # shape a single-factor reading cannot see, so it is worth drawing.
    truth_term = sim.truth_term
    is_interaction = truth_term["term_order"] > 1

    def is_crossover(rows: pd.DataFrame) -> bool:
        return bool(
            rows.loc[is_interaction[rows.index], "is_effect"].any()
            and not rows.loc[~is_interaction[rows.index], "is_effect"].any()
        )

    # `sort=False` keeps the order the simulator generated the features in, so
    # this picks the first crossover rather than the first one alphabetically.
    crossovers = [
        name for name, rows in truth_term.groupby("features", sort=False) if is_crossover(rows)
    ]
    crossover = str(crossovers[0])
    notes.add("s08 crossover feature", crossover)
    notes.add(
        "s08 truth_term for the crossover",
        truth_term[truth_term["features"] == crossover],
    )
    notes.add(
        "s08 fact.terms for the crossover",
        fact.terms.loc[
            fact.terms["features"] == crossover,
            ["terms", "f_stat", "partial_eta_sq", "log2_effect", "pval_adj"],
        ],
    )

    sig_term = sa.estimate_significance(fact, by="term")
    notes.show("s08 sig_term", sig_term)
    figure(9.0, 4.5)
    sa.draw_volcano_plot(sig_term)
    save(fig_dir, "factorial-volcano")

    figure(7.0, 5.0)
    sa.draw_interaction_plot(fact, feats=crossover, errorbar="se")
    save(fig_dir, "factorial-interaction")


def categorical_groups(fig_dir: Path, notes: Notes) -> None:
    """Section 9: a contingency table, which has no feature axis at all."""
    print("categorical comparison")
    sim = sa.simulate_categorical_groups(seed=SEED)
    cat = sa.compare_categorical_groups(**sim.args)
    notes.show("s09 cat", cat)
    notes.add("s09 cat.as_table()", cat.as_table())
    notes.add("s09 cat.association", cat.association)

    sig_cell = sa.estimate_categorical_significance(cat, by="cell")
    notes.add("s09 sig_cell.significance", sig_cell.significance)
    sig_table = sa.estimate_categorical_significance(cat, by="table", test="chisq_test")
    notes.show("s09 sig_table", sig_table)

    figure(7.0, 6.0)
    sa.draw_mosaic_plot(cat)
    save(fig_dir, "mosaic")


def association(fig_dir: Path, notes: Notes) -> None:
    """Section 14: how two features move together, and the plot that reads it."""
    print("feature-pair association")
    n_feats = N_SHOWN
    cor_mat = sa.make_block_cor(
        n_features=n_feats,
        blocks=[
            {"features": range(0, 3), "cor": COR_TIGHT},
            {"features": range(3, 5), "cor": COR_MODERATE, "against": range(5, 7)},
        ],
    )
    sim = sa.simulate_regression(n_pred=n_feats, n_factor_pred=0, cor_mat=cor_mat, seed=SEED)
    feats = list(sim.args["predictors"])
    assoc = sa.summarize_association_stats(data=sim.args["data"], feats=feats)
    notes.add("s14 assoc['design']", assoc["design"])
    notes.add("s14 pearson corr, first block", assoc["pearson"]["corr"].iloc[:3, :3])

    figure(7.0, 6.0)
    sa.draw_corrplot(assoc["pearson"]["corr"])
    save(fig_dir, "corrplot")

    figure(7.0, 6.0)
    sa.draw_corrplot(assoc["pearson"]["corr"], pvalue=assoc["pearson"]["adj_pvalue"])
    save(fig_dir, "corrplot-masked")


def _model_cor() -> Any:
    """The correlation the modelling predictors are drawn with.

    The blocks straddle the planted predictors on purpose, so that one null
    predictor is drawn correlated with a planted one. A null that correlates
    with a signal is pulled off zero by the data alone, and no number of rows
    fixes it - every section of Part 2 runs into it, so it has to be in the
    data rather than described in prose.

    R's README offsets these blocks by one, and on its own random stream that
    lands the same way. It does not here: the same offset puts both planted
    predictors inside the 0.8 block, which leaves no correlated null at all.
    """
    return sa.make_block_cor(
        n_features=8,
        blocks=[
            {"features": range(1, 3), "cor": COR_STRONG},
            {"features": range(4, 7), "cor": COR_MODERATE},
        ],
    )


def _split(data: pd.DataFrame, stratified: Any, notes: Notes, tag: str) -> tuple[Any, Any, Any]:
    dataset = sa.split_data(data=data, stratified=stratified, p_train=0.75, times=1, seed=SEED)
    notes.show(tag, dataset)
    only = next(iter(dataset.datasets))
    return dataset, dataset.datasets[only]["train_data"], dataset.datasets[only]["test_data"]


def modelling(fig_dir: Path, notes: Notes) -> None:
    """Sections 15-25: known coefficients, a clean split, and models scored on it."""
    print("modelling")
    cor_mat = _model_cor()

    # Section 15 - regression data whose coefficients are known.
    sim_reg = sa.simulate_regression(cor_mat=cor_mat, noise_sd=NOISE_SD, seed=SEED)
    # The whole table rather than the planted rows alone: `max_cor_signal` is
    # only interesting on a null, where it says how far the data alone can pull
    # that predictor off the zero it was given.
    notes.add("s15 sim_reg.truth", sim_reg.truth)
    outcome = sim_reg.args["outcome"]
    predictors = list(sim_reg.args["predictors"])
    reg_data = sim_reg.args["data"]
    # Stratify on the one predictor that is not numeric, so both halves keep its
    # level balance rather than the split being told a column name.
    factor_cols = [c for c in predictors if not pd.api.types.is_numeric_dtype(reg_data[c])]
    _, train_data, test_data = _split(
        reg_data, reg_data[factor_cols[0]] if factor_cols else None, notes, "s15 dataset"
    )

    # Section 16 - linear regression.
    lin = sa.fit_linear_regression(
        data=train_data, outcome=outcome, predictors=predictors, **CV_ARGS
    )
    notes.show("s16 lin", lin)
    notes.add("s16 lin.coef()", lin.coef()[["terms", "estimate", "pval"]])

    # Section 17 - the same call with a two-class outcome.
    sim_cls = sa.simulate_classification(cor_mat=cor_mat, seed=SEED)
    cls_outcome = sim_cls.args["outcome"]
    cls_predictors = list(sim_cls.args["predictors"])
    outcome_lv = sim_cls.args.get("outcome_lv")
    cls_data = sim_cls.args["data"]
    _, cls_train, cls_test = _split(cls_data, cls_data[cls_outcome], notes, "s17 cls dataset")

    log_fit = sa.fit_logistic_regression(
        data=cls_train,
        outcome=cls_outcome,
        predictors=cls_predictors,
        outcome_lv=outcome_lv,
        **CV_ARGS,
    )
    notes.show("s17 log_fit", log_fit)
    notes.add("s17 log_fit.coef()", log_fit.coef()[["terms", "odds_ratio", "pval"]])

    # Section 18 - recursive feature elimination, inside the resampling. The
    # resampling is left at its default here: there is no `cv` argument to turn
    # off, because an elimination with nothing held out has no score to choose a
    # subset size by.
    rfe = sa.perform_rfe(
        data=cls_train,
        outcome=cls_outcome,
        predictors=cls_predictors,
        outcome_lv=outcome_lv,
        model="logistic",
        seed=SEED,
    )
    notes.show("s18 rfe", rfe)
    notes.add("s18 rfe.profile", rfe.profile)
    notes.add("s18 rfe.selected", rfe.selected)
    notes.add(
        "s18 planted predictors",
        list(sim_cls.truth.loc[sim_cls.truth["role"] != "null", "predictors"]),
    )

    # Section 19 - stepwise, which holds nothing out and charges per parameter.
    step = sa.perform_stepwise(
        data=cls_train,
        outcome=cls_outcome,
        predictors=cls_predictors,
        outcome_lv=outcome_lv,
        model="logistic",
        criterion="AIC",
    )
    notes.show("s19 step", step)
    notes.add("s19 step.profile", step.profile)
    notes.add("s19 step.selected", step.selected)
    bic = sa.perform_stepwise(
        data=cls_train,
        outcome=cls_outcome,
        predictors=cls_predictors,
        outcome_lv=outcome_lv,
        model="logistic",
        criterion="BIC",
    )
    notes.add("s19 step.selected under BIC", bic.selected)

    # Sections 20-22 in one place: the three engines with no coefficient table,
    # fitted on the predictors the search kept so section 23 compares engines
    # rather than column sets.
    eval_rfe = sa.perform_rfe(data=train_data, outcome=outcome, predictors=predictors, seed=SEED)
    kept = list(eval_rfe.selected)
    notes.add("s23 rfe.selected on the regression half", kept)

    fitted = {
        "linear": sa.fit_linear_regression(
            data=train_data, outcome=outcome, predictors=kept, **CV_ARGS
        ),
        "lasso": sa.fit_elastic_net(
            data=train_data,
            outcome=outcome,
            predictors=kept,
            penalty="lasso",
            lambda_=LAMBDA_GRID,
            **CV_ARGS,
        ),
        "rf": sa.fit_rf(data=train_data, outcome=outcome, predictors=kept, **CV_ARGS),
        "svm": sa.fit_svm(data=train_data, outcome=outcome, predictors=kept, **CV_ARGS),
    }
    notes.add("s20 lasso coef()", fitted["lasso"].coef())
    notes.add("s21 rf coef()", fitted["rf"].coef())
    notes.add("s22 svm coef() columns", list(fitted["svm"].coef().columns))

    baseline_label = "linear"
    baseline = fitted[baseline_label]
    eval_reg = sa.evaluate_regression_models(
        baseline_model=baseline,
        new_models={k: v for k, v in fitted.items() if k != baseline_label},
        newdata=test_data,
        answer=test_data[outcome],
        baseline_label=baseline_label,
    )
    notes.show("s23 eval_reg", eval_reg)
    notes.add("s23 eval_reg.metrics", eval_reg.metrics)
    notes.add("s23 eval_reg.comparisons", eval_reg.comparisons)

    figure(7.5, 6.0)
    sa.draw_prediction_plot(eval_reg, type="overlay", anno_corr=True, anno_rsq=True)
    save(fig_dir, "eval-regression")

    # Section 24 - the same shape for a two-class outcome.
    kept_cls = list(rfe.selected)
    fitted_cls = {
        "logistic": sa.fit_logistic_regression(
            data=cls_train,
            outcome=cls_outcome,
            predictors=kept_cls,
            outcome_lv=outcome_lv,
            **CV_ARGS,
        ),
        "lasso": sa.fit_elastic_net(
            data=cls_train,
            outcome=cls_outcome,
            predictors=kept_cls,
            outcome_lv=outcome_lv,
            penalty="lasso",
            lambda_=LAMBDA_GRID,
            **CV_ARGS,
        ),
        "rf": sa.fit_rf(
            data=cls_train,
            outcome=cls_outcome,
            predictors=kept_cls,
            outcome_lv=outcome_lv,
            **CV_ARGS,
        ),
        "svm": sa.fit_svm(
            data=cls_train,
            outcome=cls_outcome,
            predictors=kept_cls,
            outcome_lv=outcome_lv,
            **CV_ARGS,
        ),
    }
    cls_baseline_label = "logistic"
    eval_cls = sa.evaluate_classification_models(
        baseline_model=fitted_cls[cls_baseline_label],
        new_models={k: v for k, v in fitted_cls.items() if k != cls_baseline_label},
        newdata=cls_test,
        answer=cls_test[cls_outcome],
        outcome_lv=outcome_lv,
        baseline_label=cls_baseline_label,
    )
    notes.show("s24 eval_cls", eval_cls)
    notes.add("s24 eval_cls.metrics", eval_cls.metrics)
    notes.add("s24 eval_cls.comparisons", eval_cls.comparisons)

    figure(7.0, 6.0)
    sa.draw_roc_curve(eval_cls, anno_auc=True)
    save(fig_dir, "eval-classification")

    # Section 25 - the prediction interface itself.
    notes.add("s25 predict, numeric", baseline.predict(newdata=test_data)[:5])
    logistic = fitted_cls[cls_baseline_label]
    notes.add("s25 predict, type='raw'", logistic.predict(newdata=cls_test, type="raw")[:5])
    notes.add(
        "s25 predict, type='prob'",
        logistic.predict(newdata=cls_test, type="prob").head(),
    )
    notes.add(
        "s25 predict, type='response'",
        logistic.predict(newdata=cls_test, type="response")[:5],
    )


def unsupervised(fig_dir: Path, notes: Notes) -> None:
    """Sections 26-27: fewer coordinates, then labels on top of them."""
    print("dimension reduction and clustering")
    n_feats = 8
    red_cor = sa.make_block_cor(
        n_features=n_feats,
        blocks=[
            {"features": range(0, 2), "cor": COR_STRONG},
            {"features": range(2, 5), "cor": COR_MODERATE},
            {"features": range(6, 8), "cor": COR_TIGHT},
        ],
    )
    sim = sa.simulate_classification(cor_mat=red_cor, seed=SEED)
    numeric = [
        c for c in sim.args["predictors"] if pd.api.types.is_numeric_dtype(sim.args["data"][c])
    ]
    red_data = sim.args["data"]

    pca = sa.perform_pca(
        data=red_data, feats=numeric, embedding_scale="features", center=True, scale=True
    )
    notes.show("s26 pca", pca)
    notes.add("s26 pca.scores", pca.scores.iloc[:, :3])
    notes.add("s26 pca.variance", pca.variance.head())

    figure(6.5, 6.0)
    sa.draw_dim_reduction_plot(pca, anno_points=True)
    save(fig_dir, "pca")

    # Eight points is a small neighbourhood, so perplexity has to come down with
    # it rather than keeping the engine default.
    perplexity = max(1.0, (len(numeric) - 1) / 3)
    tsne = sa.perform_tsne(
        data=red_data,
        feats=numeric,
        embedding_scale="features",
        center=True,
        scale=True,
        perplexity=perplexity,
        seed=SEED,
    )
    notes.show("s26 tsne", tsne)
    figure(6.5, 6.0)
    sa.draw_dim_reduction_plot(tsne, anno_points=True)
    save(fig_dir, "tsne")

    try:
        umap_res = sa.perform_umap(
            data=red_data,
            feats=numeric,
            embedding_scale="features",
            n_neighbors=3,
            seed=SEED,
        )
    except Exception as exc:  # noqa: BLE001 - the extra is optional by design
        notes.add("s26 umap", f"skipped: {exc}")
        print("  skipped UMAP (install the `umap` extra to include it)")
    else:
        notes.show("s26 umap", umap_res)
        figure(6.5, 6.0)
        sa.draw_dim_reduction_plot(umap_res, anno_points=True)
        save(fig_dir, "umap")

    # Section 27 - a clustering read against a grouping that was known already.
    clust_sim = sa.simulate_two_groups(n_feats=50, deg_log2fc=(5, 10), seed=SEED)
    clust_pca = sa.perform_pca(
        data=clust_sim.args["data"],
        feats=clust_sim.args["feats"],
        embedding_scale="samples",
    )
    n_clust = len(clust_sim.args["group_lv"])
    clust_km = sa.cluster_kmeans(
        data=clust_pca.scores,
        feats=list(clust_pca.scores.columns[1 : 1 + 2]),
        cluster_scale="samples",
        n_clust=n_clust,
        seed=SEED,
    )
    notes.show("s27 clust_km", clust_km)
    notes.add(
        "s27 planted group vs cluster",
        pd.crosstab(
            pd.Series(clust_sim.args["group"], name="group"),
            pd.Series(clust_km.assignments["cluster"].to_numpy(), name="cluster"),
        ),
    )

    figure(6.5, 6.0)
    sa.draw_dim_reduction_plot(
        clust_pca, group=clust_sim.args["group"], group_lv=clust_sim.args["group_lv"]
    )
    save(fig_dir, "cluster-pca-group")

    figure(6.5, 6.0)
    sa.draw_dim_reduction_plot(clust_pca, cluster_result=clust_km)
    save(fig_dir, "cluster-pca-cluster")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fig-dir", type=Path, default=DEFAULT_FIG_DIR)
    parser.add_argument("--text-out", type=Path, default=DEFAULT_TEXT_OUT)
    parser.add_argument(
        "--only",
        nargs="*",
        default=None,
        help="run a subset of the sections, by function name",
    )
    args = parser.parse_args(argv)

    # Wide enough that the tables the README quotes print on one line each. A
    # wrapped frame is still correct, but it cannot be pasted into a document
    # and read as the table it is.
    pd.set_option("display.width", 120)
    pd.set_option("display.max_columns", None)

    sections = {
        "two_groups": two_groups,
        "multiple_groups": multiple_groups,
        "factorial_groups": factorial_groups,
        "categorical_groups": categorical_groups,
        "association": association,
        "modelling": modelling,
        "unsupervised": unsupervised,
    }
    chosen = args.only or list(sections)
    unknown = [name for name in chosen if name not in sections]
    if unknown:
        parser.error(f"unknown section(s): {', '.join(unknown)}")

    notes = Notes()
    for name in chosen:
        sections[name](args.fig_dir, notes)
    notes.write(args.text_out)
    print(f"wrote {_shown(args.text_out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
